name: packetsender
title: Packet Sender
version: 8.8.9
summary: Packet Sender - Free TCP/UDP/SSL/HTTP Utility
icon: src/packetsender.svg
description: |
  Packet Sender - Free utility to for sending / receiving of network
  packets. TCP, UDP, SSL, and HTTP. https://packetsender.com/

source-code:
  - https://github.com/dannagle/PacketSender

contact:
  - https://packetsender.com/contact

website:
  - https://packetsender.com

issues:
  - https://github.com/dannagle/PacketSender/issues

donation:
  - https://www.paypal.com/biz/fund?id=RGDM593DYR9LJ

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

grade: stable
base: core24
confinement: strict

apps:
  packetsender:
    command: usr/local/bin/packetsender
    extensions: [kde-neon-6]
    desktop: usr/share/applications/packetsender.desktop
    plugs:
      - home
      - removable-media
      - network
      - cups

parts:
  packetsender:
    plugin: qmake
    source: src/
    qmake-project-file: PacketSenderSnap.pro

    build-packages:
      - build-essential
      - libssl-dev

    stage-packages:
      - libproxy1v5
      - libcurl4
      - cups-client
