name: packetsender
version: 8.6.7
summary: Packet Sender - Free TCP/UDP/SSL/HTTP Utility
icon: src/pslogo128.png
description: |
  Packet Sender - Free utility to for sending / receiving of network
  packets. TCP, UDP, SSL, and HTTP.

# sudo snap install packetsender*.snap --dangerous

grade: stable
base: core22
confinement: strict
architectures: [amd64]
environment:
  QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins"

apps:
  packetsender:
    command: usr/local/bin/packetsender
    desktop: usr/share/applications/packetsender.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media
      - network
      - cups
    extensions: [gnome]
      
parts:
  packetsender:
    plugin: cmake
    source: https://github.com/dannagle/PacketSender.git
    source-branch: master
    cmake-parameters:
      - $SNAPCRAFT_PART_SRC/src
    override-build: |
      cp $SNAPCRAFT_PART_SRC/src/snap/CMakeLists.txt $SNAPCRAFT_PART_SRC/src/CMakeLists.txt
      craftctl default

    build-packages:
      - build-essential
      - qt6-base-dev
      - libxkbcommon-dev
      - libgl1-mesa-dev
      - libglvnd-dev
      - libssl-dev

    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6widgets6
      - libqt6network6
      - libqt6printsupport6
      - libcurl4
      - qt6-translations-l10n
      - qt6-gtk-platformtheme
      - qt6-qpa-plugins
      - qt6-wayland
      - cups-client
  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280#heading--cleanup-part
  #
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - packetsender
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
    override-prime: |
      set -eux
      for snap in "core22" "gnome" ; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      
