name: packetsender
title: Packet Sender
version: 8.8.9
summary: Packet Sender - Free TCP/UDP/SSL/HTTP Utility
icon: src/packetsender.svg
description: |
  Packet Sender - Free utility to for sending / receiving of network
  packets. TCP, UDP, SSL, and HTTP. https://packetsender.com/

source-code:
  - https://github.com/dannagle/PacketSender

contact:
  - https://packetsender.com/contact

website:
  - https://packetsender.com

issues:
  - https://github.com/dannagle/PacketSender/issues

donation:
  - https://www.paypal.com/biz/fund?id=RGDM593DYR9LJ


platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

# sudo snap install packetsender*.snap --dangerous

grade: stable
base: core24
confinement: strict

plugs:
  kf6-core24:
    interface: content
    target: $SNAP/kf6
    default-provider: kf6-core24
  gpu-2404:
      interface: content
      target: $SNAP/gpu-2404
      default-provider: mesa-2404

apps:
  packetsender:
    command: usr/local/bin/packetsender
    desktop: usr/share/applications/packetsender.desktop
    extensions:
      - kde-neon-6
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media
      - network
      - cups
      
parts:
  packetsender:
    plugin: qmake
    source: src/
    qmake-project-file: PacketSenderSnap.pro
    qmake-major-version: 6
    build-environment:
      - QT_SELECT: qt6

    build-packages:
      - build-essential
      - qt6-base-dev
      - libxkbcommon-dev
      - qt6-declarative-dev
      - libgl1-mesa-dev
      - libglvnd-dev
      - libssl-dev

    stage-packages:
      - libproxy1v5
      - libcurl4
      - cups-client